# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_loglikelihood_pen_noderiv <- function(theta, X, y, c, sp, S, K) {
    .Call(`_flexl_find_loglikelihood_pen_noderiv`, theta, X, y, c, sp, S, K)
}

find_loglikelihood_pen_with_grad <- function(theta, X, y, c, sp, S, K) {
    .Call(`_flexl_find_loglikelihood_pen_with_grad`, theta, X, y, c, sp, S, K)
}

find_loglikelihood_pen <- function(theta, X, y, c, sp, S, K) {
    .Call(`_flexl_find_loglikelihood_pen`, theta, X, y, c, sp, S, K)
}

