# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_loglikelihood_cluster_Cpp <- function(f0_c, fx_c, y_c, sigma) {
    .Call(`_flexl_find_loglikelihood_cluster_Cpp`, f0_c, fx_c, y_c, sigma)
}

